// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5d46bMR5kII6waw6oMaFe_GRFeKj-BHY',
    appId: '1:540467209666:web:bd4f5088a73fc87f99e25b',
    messagingSenderId: '540467209666',
    projectId: 'flutter-projet-final',
    authDomain: 'flutter-projet-final.firebaseapp.com',
    storageBucket: 'flutter-projet-final.firebasestorage.app',
    measurementId: 'G-LBJL2NTP27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfoxrTmVNsm9r0NO9IKDB5EAxAM9jUadg',
    appId: '1:540467209666:android:0e5bc0970b01e27699e25b',
    messagingSenderId: '540467209666',
    projectId: 'flutter-projet-final',
    storageBucket: 'flutter-projet-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqu1Pz3FDvzhjQknMuNjw_0bYkN0u9CjY',
    appId: '1:540467209666:ios:f169fde9fbc3a54e99e25b',
    messagingSenderId: '540467209666',
    projectId: 'flutter-projet-final',
    storageBucket: 'flutter-projet-final.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjetFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqu1Pz3FDvzhjQknMuNjw_0bYkN0u9CjY',
    appId: '1:540467209666:ios:f169fde9fbc3a54e99e25b',
    messagingSenderId: '540467209666',
    projectId: 'flutter-projet-final',
    storageBucket: 'flutter-projet-final.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjetFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5d46bMR5kII6waw6oMaFe_GRFeKj-BHY',
    appId: '1:540467209666:web:bdf07a7b2bb91b1399e25b',
    messagingSenderId: '540467209666',
    projectId: 'flutter-projet-final',
    authDomain: 'flutter-projet-final.firebaseapp.com',
    storageBucket: 'flutter-projet-final.firebasestorage.app',
    measurementId: 'G-H418TYB9BE',
  );
}